#!/usr/bin/env bash

set -e
ENVIRONMENT=$1
export RAILS_ENV=$1
OLD_ENV=$(git remote -v | sed -e '/origin/d' -e '/push/d' -e 's/^.*-//' -e 's/\.git.*$//')

if [ "$ENVIRONMENT" != "production" ]; then
  if [ "$ENVIRONMENT" != "staging" ]; then
    echo "Usage: ./script/deploy (staging|production)"
    exit 1
  fi
fi

echo "Pushing to ${ENVIRONMENT} heroku remote"
if [ "$ENVIRONMENT" == "staging" ]; then
  git push -f staging develop:master
  APP_NAME=not-suck-cms-staging
else
  git push production master:master
  APP_NAME=not-suck-cms
fi

echo "Running db:migrate for ${APP_NAME} on heroku"
heroku rake db:migrate --app $APP_NAME

echo "Clearing jobs on heroku"
heroku rake jobs:clear --app $APP_NAME

echo "restarting ${APP_NAME} on heroku"
heroku restart --app $APP_NAME

echo "hitting #{APP_NAME} to wake it"
curl "http://${APP_NAME}.heroku.com" &> /dev/null &
